export default Object.freeze({
  ACCOUNT: "Account",
  FEED: "Feed",
  LOGIN: "Login",
  REGISTER: "Register",
  WELCOME: "Welcome",
  HOME: "Home",
  SEARCH: "Search",
  PROFILE_SCREEN: "ProfileScreen",
  PROFILE_TAB: "ProfileTab",
  FAVORITE: "Favorite",
  EXPLORE_TAB: "ExploreTab",
  EXPLORE_SCREEN: "ExploreScreen",
  PLAN_DETAILS: "PlanDetails",
  ADD_CONTENT_TAB: "AddContentTab",
  ADD_CONTENT_SCREEN: "AddContentScreen",
  NEW_POST: "NewPost",
  NEW_CITY: "NewCity",
  SETTINGS: "Settings",
} as { [key: string]: string; })